deployment:
tasks:
- export REPOPATH=/home/osipovao/repositories/YULTA-complex/yulta-complex_site/build/*
- export SITEPATH=/home/osipovao/repositories/YULTA-complex/yulta-complex_site/build/*
- /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
