---
deployment:
  tasks:
    - export REPOPATH=/home/osipovao/repositories/YULTA-complex/
    - export SITEPATH=/home/osipovao/repositories/YULTA-complex/yulta-complex_site/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
