---
deployment:
  tasks:
    - export REPOPATH=/home/yultaby/repositories/YULTA-complex/yulta-complex_site/.presite/
    - export SITEPATH=/home/yultaby/public_html/
    - /bin/rsync -rav --del $REPOPATH $SITEPATH

